"""Hatchling custom build hook — generates src/clawrium/_version.py at build time.

Writes ``__version__`` and ``__git_sha__`` into a standalone module that ships
inside the wheel.  At runtime ``clawrium/__init__.py`` imports from here when
available (installed package) and falls back to ``importlib.metadata`` for
editable installs.
"""

from __future__ import annotations

import subprocess
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_ROOT = Path(__file__).resolve().parent
_VERSION_FILE = _ROOT / "src" / "clawrium" / "_version.py"


def _get_version() -> str:
    """Return the package version string."""
    try:
        return version("clawrium")
    except PackageNotFoundError:
        pass
    # Fallback: parse pyproject.toml
    import tomllib

    pyproject = _ROOT / "pyproject.toml"
    if pyproject.exists():
        with open(pyproject, "rb") as fh:
            data = tomllib.load(fh)
        return data.get("project", {}).get("version", "0.0.0")
    return "0.0.0"


def _get_git_sha() -> str:
    """Return the short git commit SHA, or ``"unknown"`` on failure."""
    try:
        sha = (
            subprocess.check_output(
                ["git", "rev-parse", "--short", "HEAD"],
                cwd=str(_ROOT),
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
        return sha if sha else "unknown"
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return "unknown"


class CustomBuildHook(BuildHookInterface):
    """Hatchling build hook that generates ``_version.py`` before the build."""

    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:  # noqa: ARG002
        pkg_version = _get_version()
        git_sha = _get_git_sha()

        _VERSION_FILE.write_text(
            f"# AUTO-GENERATED by hatch_build.py — do not edit.\n"
            f"__version__ = {pkg_version!r}\n"
            f"__git_sha__ = {git_sha!r}\n"
        )

        # Ensure the generated file is picked up by the build.
        build_data["artifacts"].append("src/clawrium/_version.py")
