"""Provider management for Clawrium.

This package provides:
- Provider storage operations (CRUD for provider configurations)
- Model catalog with metadata for all supported providers
- Search and validation functions for models
"""

from clawrium.core.providers.models import (
    CatalogLoadError,
    ModelCatalog,
    ModelInfo,
    ModelNotFoundError,
    ProviderModels,
    ProviderNotFoundError,
    get_catalog_providers,
    get_model_count,
    get_model_ids_for_provider,
    get_models_for_provider,
    load_model_catalog,
    search_models,
    validate_model_id,
)
from clawrium.core.providers.storage import (
    PROVIDER_MODELS,
    PROVIDERS_FILE,
    DuplicateProviderError,
    InvalidOllamaUrlError,
    InvalidProviderNameError,
    InvalidProviderTypeError,
    OllamaConnectionError,
    ProvidersFileCorruptedError,
    add_provider,
    fetch_ollama_models,
    get_models_for_type,
    get_provider,
    get_provider_api_key,
    get_provider_aws_credentials,
    get_provider_instance_key,
    load_providers,
    remove_provider,
    remove_provider_api_key,
    remove_provider_aws_credentials,
    save_providers,
    set_provider_api_key,
    set_provider_aws_credentials,
    update_provider,
    validate_ollama_url,
    validate_provider_name,
    validate_provider_type,
)

__all__ = [
    # Models module exports (JSON catalog)
    "load_model_catalog",
    "get_models_for_provider",
    "get_model_ids_for_provider",
    "validate_model_id",
    "search_models",
    "get_catalog_providers",
    "get_model_count",
    "ModelNotFoundError",
    "ProviderNotFoundError",
    "CatalogLoadError",
    "ModelInfo",
    "ProviderModels",
    "ModelCatalog",
    # Storage module exports
    "PROVIDERS_FILE",
    "PROVIDER_MODELS",
    "load_providers",
    "save_providers",
    "add_provider",
    "get_provider",
    "update_provider",
    "remove_provider",
    "validate_provider_name",
    "validate_provider_type",
    "validate_ollama_url",
    "get_models_for_type",
    "fetch_ollama_models",
    "get_provider_instance_key",
    "set_provider_api_key",
    "get_provider_api_key",
    "remove_provider_api_key",
    "set_provider_aws_credentials",
    "get_provider_aws_credentials",
    "remove_provider_aws_credentials",
    "ProvidersFileCorruptedError",
    "DuplicateProviderError",
    "InvalidProviderTypeError",
    "InvalidProviderNameError",
    "OllamaConnectionError",
    "InvalidOllamaUrlError",
]
