# /// script
# requires-python = ">=3.10"
# dependencies = ["playwright>=1.40"]
# ///
# ====================================================================
#  GENERATED by docs/demos/lib/pw_compile.py — DO NOT EDIT.
#  Source of truth: /home/devashish/workspace/ric03uec/clawrium/docs/demos/20260621-clawrium-gui-walkthrough/scenes.yaml
#  Compiled at: 2026-06-22T04:14:54+00:00
# ====================================================================
"""Playwright driver for the Clawrium GUI walkthrough demo."""
from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

from playwright.sync_api import Page, sync_playwright


DEMO_DIR = Path(__file__).resolve().parent
VIEWPORT = {"width": 1400, "height": 900}
BASE_URL = 'http://127.0.0.1:36000'
COLOR_SCHEME = 'light'
REDUCED_MOTION = 'reduce'


def main() -> int:
    video_dir = DEMO_DIR / "_video_raw"
    video_dir.mkdir(exist_ok=True)
    for old in video_dir.glob("*.webm"):
        old.unlink()

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True, channel="chrome")
        context = browser.new_context(
            viewport=VIEWPORT,
            record_video_dir=str(video_dir),
            record_video_size=VIEWPORT,
            color_scheme=COLOR_SCHEME,
            reduced_motion=REDUCED_MOTION,
        )
        page = context.new_page()


        # ---- intro title card ----
        title_uri = (DEMO_DIR / "cards" / "title.html").as_uri()
        page.goto(title_uri, wait_until="domcontentloaded")
        page.wait_for_timeout(5000)


        # ---- initial app load ----
        page.goto(BASE_URL.rstrip("/") + "/", wait_until="domcontentloaded")
        page.wait_for_timeout(500)

        # ---- scenes ----

        play_scene_01(page)

        play_scene_02(page)

        play_scene_03(page)

        play_scene_04(page)

        play_scene_05(page)

        play_scene_06(page)

        play_scene_07(page)



        # ---- outro card ----
        outro_uri = (DEMO_DIR / "cards" / "outro.html").as_uri()
        page.goto(outro_uri, wait_until="domcontentloaded")
        page.wait_for_timeout(6000)


        context.close()
        browser.close()

    return finalize_recording()



def play_scene_01(page: Page) -> None:
    """[scene 01] Dashboard"""
    print('[scene 01] Dashboard', flush=True)
    start = time.monotonic()

    page.locator("h1:has-text('Dashboard')").first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 9.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_02(page: Page) -> None:
    """[scene 02] Agents"""
    print('[scene 02] Agents', flush=True)
    start = time.monotonic()

    page.locator("aside nav a[href='/agents']").first.click()

    page.wait_for_url('**/agents', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 8.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_03(page: Page) -> None:
    """[scene 03] Topology"""
    print('[scene 03] Topology', flush=True)
    start = time.monotonic()

    page.locator("aside nav a[href='/topology']").first.click()

    page.wait_for_url('**/topology', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 8.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_04(page: Page) -> None:
    """[scene 04] Providers"""
    print('[scene 04] Providers', flush=True)
    start = time.monotonic()

    page.locator("aside nav a[href='/providers']").first.click()

    page.wait_for_url('**/providers', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 11.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_05(page: Page) -> None:
    """[scene 05] Skills"""
    print('[scene 05] Skills', flush=True)
    start = time.monotonic()

    page.locator("aside nav a[href='/skills']").first.click()

    page.wait_for_url('**/skills', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 8.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_06(page: Page) -> None:
    """[scene 06] Integrations"""
    print('[scene 06] Integrations', flush=True)
    start = time.monotonic()

    page.locator("aside nav a[href='/integrations']").first.click()

    page.wait_for_url('**/integrations', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 8.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def play_scene_07(page: Page) -> None:
    """[scene 07] Settings"""
    print('[scene 07] Settings', flush=True)
    start = time.monotonic()

    page.locator("aside a[href='/settings']").first.click()

    page.wait_for_url('**/settings', timeout=10_000)

    page.locator('h1').first.wait_for(timeout=10_000)

    elapsed = time.monotonic() - start
    remaining = max(0.0, 11.0 - elapsed)
    page.wait_for_timeout(int(remaining * 1000))



def finalize_recording() -> int:
    video_dir = DEMO_DIR / "_video_raw"
    webms = sorted(video_dir.glob("*.webm"))
    if not webms:
        print("ERROR: Playwright produced no WebM", file=sys.stderr)
        return 1
    target_webm = DEMO_DIR / "recording.webm"
    webms[-1].replace(target_webm)
    for stray in video_dir.glob("*"):
        stray.unlink()
    video_dir.rmdir()
    print(f"Recorded: {target_webm.name}")

    target_mp4 = DEMO_DIR / "recording.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-i", str(target_webm),
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-crf", "20",
            "-preset", "fast",
            "-loglevel", "error",
            str(target_mp4),
        ],
        check=True,
    )
    print(f"Transcoded: {target_mp4.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
